### ISSUE TITLE
How to use 'metric' syntax?

### ISSUE THREAD

**Issue by Taaewoo** [KCL-Planning/SMTPlan#3]
Hello all,

I tested car_nodrag, but we did not get the results we wanted.

We have increased the uplimit of acceleration and set the condition v = 0 in the stop action to v> 0. 
Of course, we modified the conditions so that engine explode does not occur. In other words, we have 
eliminated the limitation of acceleration and made it not stop at the target point. According to the 'metric' syntax, the planner need to increase the speed by increasing the acceleration continuously, but the result does not continuously increase the acceleration. Therefore, the minimized total time of 'metcric' syntax is not reached.

Thank you!

**Comment by m312z** [comment]
Hello Taaewoo,

Currently SMTPlan does not support a metric.
It will try to find a plan that satisfies the goals without taking the metric into account.

This is functionality that I'll be adding as soon as I have time to work more on the code. I will leave this issue open until I have done so.

There is still a way to introduce a metric. If you run SMTPlan with the options "-l [number]" and "n" then (1) an encoding with [number] happenings will be generated, and (2) the encoding will be printed to screen instead of solved.

This allows you to modify the encoding by hand and introduce the desired optimisation.

Michael

**Comment by m312z** [comment]
Hello again,

I should have mentioned previously -- although you can add an optimisation manually to the generated SMT file, this is not necessarily an optimal solution to the planning problem! It will be optimal only for that number of happenings, and it is not guaranteed that a better solution does not exist at a deeper level.

(This is a drawback of this approach to planning.)

Michael
